// <auto-generated />
using System;
using GestionEstudiantesWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionEstudiantesWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250419024306_initial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCarrera");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Docente", b =>
                {
                    b.Property<int>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDocente");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstudiante");

                    b.HasIndex("IdCarrera");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdNivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMateria");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdNivel");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Matricula", b =>
                {
                    b.Property<int>("IdMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatricula"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.HasKey("IdMatricula");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdMateria");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Nivel", b =>
                {
                    b.Property<int>("IdNivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNivel"));

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdNivel");

                    b.HasIndex("IdCarrera");

                    b.ToTable("Niveles");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Nota", b =>
                {
                    b.Property<int>("IdNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNota"));

                    b.Property<decimal>("Calificacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("IdMatricula")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdNota");

                    b.HasIndex("IdMatricula");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Estudiante", b =>
                {
                    b.HasOne("GestionEstudiantesWeb.Models.Carrera", "oCarrera")
                        .WithMany("Estudiantes")
                        .HasForeignKey("IdCarrera")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("oCarrera");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Materia", b =>
                {
                    b.HasOne("GestionEstudiantesWeb.Models.Docente", "oDocente")
                        .WithMany("Materias")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionEstudiantesWeb.Models.Nivel", "oNivel")
                        .WithMany("Materias")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("oDocente");

                    b.Navigation("oNivel");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Matricula", b =>
                {
                    b.HasOne("GestionEstudiantesWeb.Models.Estudiante", "oEstudiante")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionEstudiantesWeb.Models.Materia", "oMateria")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("oEstudiante");

                    b.Navigation("oMateria");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Nivel", b =>
                {
                    b.HasOne("GestionEstudiantesWeb.Models.Carrera", "oCarrera")
                        .WithMany("Niveles")
                        .HasForeignKey("IdCarrera")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("oCarrera");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Nota", b =>
                {
                    b.HasOne("GestionEstudiantesWeb.Models.Matricula", "oMatricula")
                        .WithMany("Notas")
                        .HasForeignKey("IdMatricula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("oMatricula");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Carrera", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("Niveles");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Docente", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Estudiante", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Materia", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Matricula", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("GestionEstudiantesWeb.Models.Nivel", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
